[INISystem]
BasedOn=GenericWindow.ini

[OptionsWindow]

[lblDetailLevel]
ToolTip=Select the level of detail. Lower levels will reduce visual effects and increase performance.
Enabled=False
Visible=False

[ddDetailLevel]
ToolTip=Select the level of detail. Lower levels will reduce visual effects and increase performance.
Enabled=False
Visible=False

[lblRenderer]
ToolTip=Select the DDraw wrapper to use. If you experience graphical or performance issues, try a different wrapper.

[ddRenderer]
ToolTip=Select the DDraw wrapper to use. If you experience graphical or performance issues, try a different wrapper.

[chkBackBufferInVRAM]
Text=Back Buffer in Video Memory
ToolTip=Enable back buffer in VRAM. Reduces performance, but is necessary on some systems.
Enabled=False
Visible=False

; ==========================
; Updater Menu Items
; ==========================

[UpdaterOptionsPanelExtraControls]
0=lblUpdateChannel:XNALabel
1=ddUpdateChannel:FileSettingDropDown
2=lblUpdateChannelDescription:XNALabel
3=btnCncnetSupport:XNALinkButton

[lblUpdateChannel]
Location=12,240
Size=90,24
Text=Update Channel:

[btnForceUpdate]
Location=407,213
Size=133,23

[ddUpdateChannel]
Location=115,238
Size=280,21
Items=Develop
DefaultValue=0
CheckFilePresence=yes
ResetUnselectableItem=yes
ForceApplyUnselectableItem=no
RestartRequired=true
Item0File0=Resources/UpdaterConfig_Dev.ini,Resources/UpdaterConfig.ini,OverwriteOnMismatch
ToolTip=Switch between update Channels. Requires client restart.
Enabled=true

[lblUpdateChannelDescription]
Location=12,264
Text=**WARNING**:@Using the Beta or Dev channel may bring unexpected errors or behavior.@It is meant to allow public testing of upcom

[btnCncnetSupport]
IdleTexture=133pxbtn.png
HoverTexture=133pxbtn_c.png
Location=12,315
Size=133,21
Text=CnCNet Support
URL=https://discord.com/channels/188156159620939776/1060560955186085888

[GameOptionsPanelExtraControls]
0=chkUseSmallInfantry:SettingCheckBox
1=chkLimitCpuUsage:SettingCheckBox
2=chkPlayEnglishIntro:SettingCheckBox
3=chkVideoInterlaceMode:SettingCheckBox
4=chkNoCD:SettingCheckBox
;5=chkCounterstrikeEnabled:SettingCheckBox
;6=chkAftermathEnabled:SettingCheckBox
7=chkSkipScoreScreen:SettingCheckBox
8=chkRandomStartingSong:SettingCheckBox
9=chkMouseWheelScrolling:SettingCheckBox
10=chkSlowerScrollrate:SettingCheckBox

[lblPlayerName]
Location=12,212

[tbPlayerName]
Location=113,210

[btnConfigureHotkeys]
Location=12,290

[lblNotice]
Location=12,240

[chkTooltips]
Location=12,126
ToolTip=Enable in-game tooltips.
Enabled=False
Visible=False

[chkScrollCoasting]
Location=12,54
ToolTip=Enable smooth scrolling.
DefaultValue=true
SettingSection=Options
SettingKey=DisableEdgeScrolling
EnabledSettingValue=false
DisabledSettingValue=true
Enabled=false
Visible=false

[chkTargetLines]
Location=12,78
ToolTip=Show lines between selected units and targets.@Green lines indi
Enabled=False
Visible=False

[chkQuickExit]
Location=12,102
Text=Quick Exit
ToolTip=When enabled, you can exit the game by pressing Alt+F4
DefaultValue=true
SettingSection=Options
SettingKey=QuickExit
Enabled=False
Visible=False

[chkShowHiddenObjects]
Location=242,126
ToolTip=Display a visual indicator when an object is visually hidden be
Enabled=False
Visible=False

[chkUseSmallInfantry]
Location=12,54
Text=Enable small infantry
ToolTip=
DefaultValue=No
SettingSection=Options
SettingKey=UseSmallInfantry
WriteSettingValue=yes
EnabledSettingValue=Yes
DisabledSettingValue=No

[chkLimitCpuUsage]
Location=12,78
Text=Limit CPU Usage
ToolTip=
DefaultValue=No
SettingSection=Options
SettingKey=LimitCpuUsage
EnabledSettingValue=Yes 
DisabledSettingValue=No

[chkPlayEnglishIntro]
Location=12, 102
Text=Play intro cinematic
ToolTip=
DefaultValue=No
SettingSection=Options
SettingKey=PlayEnglishIntro
WriteSettingValue=yes
EnabledSettingValue=Yes
DisabledSettingValue=No

[chkVideoInterlaceMode]
Location=12, 126
Text=Deinterlace videos
ToolTip=
DefaultValue=No
SettingSection=Options
SettingKey=VideoInterlaceMode
WriteSettingValue=yes
EnabledSettingValue=Yes
DisabledSettingValue=No

[chkNoCD]
Location=12, 150
Text=No CD Required 
ToolTip=
DefaultValue=Yes
SettingSection=Options
SettingKey=NoCD
WriteSettingValue=yes
EnabledSettingValue=Yes
DisabledSettingValue=No

;[chkCounterstrikeEnabled]
;Location=242, 54
;Text=Enable Counterstrike expansion
;ToolTip=
;DefaultValue=No
;SettingSection=Options
;SettingKey=CounterstrikeEnabled
;EnabledSettingValue=Yes
;DisabledSettingValue=No
;
;[chkAftermathEnabled]
;Location=242, 78
;Text=Enable Aftermath expansion
;ToolTip=
;DefaultValue=No
;SettingSection=Options
;SettingKey=AftermathEnabled
;EnabledSettingValue=Yes
;DisabledSettingValue=No

[chkSkipScoreScreen]
Location=242, 102
Text=Skip Score Screen
ToolTip=
DefaultValue=No
SettingSection=Options
SettingKey=SkipScoreScreen
WriteSettingValue=yes
EnabledSettingValue=Yes
DisabledSettingValue=No

[chkRandomStartingSong]
Location=242, 126
Text=Random Starting Song
ToolTip=
DefaultValue=Yes
SettingSection=Options
SettingKey=RandomStartingSong
WriteSettingValue=yes
EnabledSettingValue=Yes
DisabledSettingValue=No

[chkMouseWheelScrolling]
Location=242, 150
Text=Mouse Wheel Scrolling
ToolTip=
DefaultValue=Yes
SettingSection=Options
SettingKey=MouseWheelScrolling
WriteSettingValue=yes
EnabledSettingValue=Yes
DisabledSettingValue=No

[trbScrollRate]
SettingKey=ScrollRate

[chkSlowerScrollrate]
Location=242, 78
Text=Limit scroll rate
ToolTip=
SettingSection=Options
SettingKey=SlowerScrollrate
DefaultValue=No
WriteSettingValue=yes
EnabledSettingValue=Yes
DisabledSettingValue=No
